### ISSUE TITLE
Add localisation

### ISSUE THREAD

**Issue by CKPEIIKA** [quantum-entangled/gam-ml-test#19]
It would be great to localize the project (at least russian language) from the early beginning using python-i18n or something more fancy. Later locale may be set on the fly.

**Comment by quantum-entangled** [comment]
It's the great idea, but initially we decided not to do it at one of our department meetings last year, because it is much simpler to talk and write about ML stuff in English. Yes, we can display some unrelated massages/instructions automatically, if there is some sense, but, as I remember, everyone has agreed to read English.

**Comment by quantum-entangled** [comment]
I will close it for now.
